name: duf
base: core18
adopt-info: duf # Obtain version metadata from the 'duf' part
license: MIT
summary: Disk Usage/Free Utility
description: |
  ## Features
  
  - User-friendly, colorful output
  - Adjusts to your terminal's width
  - Sort the results according to your needs
  - Groups & filters devices
  - Can conveniently output JSON

  You can simply start duf without any command-line arguments:
  
  ```
  duf
  ```
  
  If you want to list everything (including pseudo, duplicate, inaccessible file systems):
  
  ```
  duf --all
  ```

  You can hide individual tables:

  ```
  duf --hide-local --hide-network --hide-fuse --hide-special --hide-loops --hide-binds
  ```

  List inode information instead of block usage:

  ```
  duf --inodes
  ```

  Sort the output:

  ```
  duf --sort size
  ```

  Valid keys are: `mountpoint`, `size`, `used`, `avail`, `usage`, `inodes`,
  `inodes_used`, `inodes_avail`, `inodes_usage`, `type`, `filesystem`.

  Show or hide specific columns:

  ```
  duf --output mountpoint,size,usage
  ```

  Valid keys are: `mountpoint`, `size`, `used`, `avail`, `usage`, `inodes`,
  `inodes_used`, `inodes_avail`, `inodes_usage`, `type`, `filesystem`.

  If you prefer your output as JSON:

  ```
  duf --json
  ```
  
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

parts:
  license: # Include the license in the snap package
    plugin: dump
    source: https://github.com/muesli/duf.git
    source-type: git
    override-pull: | # Checkout the latest tag (=latest release)
      snapcraftctl pull
      VER=$(git describe --abbrev=0 --tags)
      git checkout $VER
    prime: 
      - LICENSE

  duf:
    plugin: go
    go-importpath: parts/duf
    source: https://github.com/muesli/duf.git
    source-type: git
    override-pull: | # Checkout the latest tag (=latest release) and set the snap's version string
      snapcraftctl pull
      VER=$(git describe --abbrev=0 --tags)
      git checkout $VER
      snapcraftctl set-version $VER 
    

apps:
  duf:
    command: duf
    plugs:
      - mount-observe
